[package]
name = "mk42-worker"
version = "0.1.0"
edition = "2021"
authors = ["Christoph Ebert"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
colored = "2.0.0"
chrono = "0.4.19"
rayon = "1.5.3"
